### PR TITLE
adding files to do pull request

### PR DESCRIPTION
**Pull request by debragordon**
opening a pull request ... nothing is ready for review

### CODE REVIEW

**Comment by debragordon** [comment]
ready for review @zoeames @ncgonz (as ready as it is going to be)

**Comment by debragordon** [comment]
@zoeames @ncgonz ready for review (as ready as it is going to be)

**Comment by zoeames** [comment]
I am not seeing any click events work.  check and see if something didn't get pushed up

**Comment by debragordon** [comment]
very weird ... everything was pushed up, directory clean ... not sure what I getting the error that the carDescription wasn't defined ... it was working when pushed up

I haven't looked at this in weeks ... I will have to review after this group work

**Comment by debragordon** [comment]
I just checked ... switched back and forth from branches ... tried to push again to quiz and it said it wouldn't let me, everything up to date.

It should work?? I didn't get any errors ... @zoeames

**Pull request closed without merging**
